// appdokter/src/app/layout/obat/list-obat/list-obat.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-list-obat',
  templateUrl: './list-obat.component.html',
  styleUrls: ['./list-obat.component.scss']
})
export class ListObatComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div [@routerTransition]>
<<<<<<< HEAD
  
  <div class="row" style="margin-top:20px;">
    <div class="col-lg-12">
      <table class="table table-bordered table-striped table-hover table-condensed" style="overflow:hidden;margin-bottom:-3px">
        <thead>
          <tr>
            <th class="text-center" style="width:72px;">No.</th>
            <th class="text-center" style="width:218px;">Nama</th>
            <th class="text-center" style="width:57px;">Jenis</th>
            <th class="text-center" style="width:137px;">Harga Jual</th>
            <th class="text-center" style="width:134px;">Harga Beli</th>
            <th class="text-center" style="width:104px;">Stok</th>
            <th class="text-center" style="width:195px;">Satuan</th>
            <th class="text-center" style="width:195px;">Tanggal Input</th>
           
          </tr>
        </thead>
     
        <tbody>
          <tr *ngFor="let l of listObat; let i=index">
  
            <td ></td>
            <td >{{l.nama}}</td>
            <td >{{l.jenisId}}</td>
            <td class="text-right" >{{l.hargaJual|number:'.2-2'}}</td>
            <td class="text-right" >{{l.hargaBeli|number:'.2-2'}}</td>
            <td class="text-right" >{{l.stok|number}}</td>
            <td ></td>
            <td>{{l.CreatedDate}}</td>
          
  
          </tr>
          <tr *ngIf=" listObat.length === 0">
            <td colspan="8" align="center">Data not available</td>
          </tr>
        </tbody>
      </table>
  
    </div>
  </div>
=======
  <h2 class="text-muted">Obat </h2>
  <div class="row">
    <div class="col-md-12 col-xs-12 col-lg-12 right">
      <button class="btn btn-primary">Add Obat</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-xs-12 col-lg-12">
      <div class="card-body table-responsive">
        <table class="table table-hover table-striped" [mfData]="data" #mf="mfDataTable" [mfRowsOnPage]="5">
          <thead>
            <tr>
              <th>No</th>
              <th>
                <mfDefaultSorter by="name">Kode Obat</mfDefaultSorter>

              </th>
              <th> <mfDefaultSorter by="name">Nama Obat</mfDefaultSorter>
              </th>
              <th> <mfDefaultSorter by="name">Harga Jual</mfDefaultSorter></th>
              <th> <mfDefaultSorter by="name">Stock</mfDefaultSorter></th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1.</td>
              <td>P001</td>
              <td>Bodrex</td>
              <td>5000</td>
              <td>50</td>
              <td>edit || delete</td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="6">
                <mfBootstrapPaginator [rowsOnPageSet]="[5,10,25]"></mfBootstrapPaginator>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>

>>>>>>> 43f65ddba130c73af607be9f8394a75c93519134
</div>

// dokterlara/resources/assets/js/pages/obat/listObat.vue
<template>
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-md-8 col-lg-8"></div>
      <div class="col-xs-3 col-md-3 col-lg-3">
        <div class="actions">
          <a class="btn btn-default">
            <router-link :to="{path: '/add-product'}">
              <span class="glyphicon glyphicon-plus"></span>
              Add product
            </router-link>
          </a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-12 col-lg-12">
        <div class="table table-borderless" id="table">
          <table class="table table-borderless" id="table">
            <thead>
              <tr>
                <th class="text-center" style="width:72px;">No.</th>
                <th class="text-center" style="width:218px;">Nama</th>
                <th class="text-center" style="width:57px;">Jenis</th>
                <th class="text-center" style="width:137px;">Harga Jual</th>
                <th class="text-center" style="width:134px;">Harga Beli</th>
                <th class="text-center" style="width:104px;">Stok</th>
                <th class="text-center" style="width:195px;">Satuan</th>
                <th class="text-center" style="width:195px;">Tanggal Input</th>
                <th class="text-center">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="l of listObat" :key="l.id">
                <td></td>
                <td>{{l.nama}}</td>
                <td>{{l.jenisId}}</td>
                <td class="text-right">{{l.hargaJual|number:'.2-2'}}</td>
                <td class="text-right">{{l.hargaBeli|number:'.2-2'}}</td>
                <td class="text-right">{{l.stok|number}}</td>
                <td></td>
                <td>{{l.CreatedDate}}</td>
                <td>
                  <a class="btn btn-warning btn-xs">
                    <router-link :to="{name: 'product-edit', params: {id: l.id}}">
                      <span class="glyphicon glyphicon-pencil"></span>Edit
                    </router-link>
                  </a>
                  <a class="btn btn-danger btn-xs" @click.prevent="deleteObat(l.id)">
                    <span class="glyphicon glyphicon-trash"></span>Delete
                  </a>
                </td>
              </tr>
              <tr v-if="listObat.length === 0">
                <td colspan="9" align="center">Data not available</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
//import baseUrl from '../../variable.js'
export default {
  name: "obat",
  data() {
    return {
      listObat: []
    };
  },
  created() {
    let uri =  "obat";
     this.myApi.get(uri).then(response => {
      this.listObat = response.data.data;
    });
  },
  methods: {
    deleteObat(id) {
      let uri =  `obat/${id}`;
      this.myApi.delete(uri).then(response => {
        this.listObat.splice(this.listObat.indexOf(id), 1);
      });
    }
  }
};
</script>
